### ISSUE TITLE
Have you had a compile version for Windows

### ISSUE THREAD

**Issue by Watanyou** [graspit-simulator/graspit#104]
I've tried to compile but struck at Cmake for a week and I've run out of time. 

![image](https://cloud.githubusercontent.com/assets/9107467/24423290/a737a0bc-1426-11e7-9f1b-7e4580b04936.png)

If you has a compiled version can I get it, please.

Thank you so much.

**Comment by jvarley** [comment]
I do not have a compiled version for windows.  Did you install BLAS? In Linux it would be 
```
sudo apt-get install libblas-dev
```
