### ISSUE TITLE
graspit_simulator.exe has stopped working

### ISSUE THREAD

**Issue by TirawatT** [graspit-simulator/graspit#105]
![graspit_error](https://cloud.githubusercontent.com/assets/25239106/24448266/cd51b220-149d-11e7-8909-39a624448aec.PNG)

Error , when I'm run graspit_simulator.exe 

I'm build graspit 3.0 and follow http://graspit-simulator.github.io/build/html/index.html 
and Run graspit_simulator.exe on machine windows 7 64

what's wrong ?

Thank you so much.

**Comment by jvarley** [comment]
I have very little experience running GraspIt! on windows unfortunately.   If you are able to get a stack trace I might be able to help a bit more.

@JenniferBuehler  would probably be more helpful, but I would image she would need more information as well.

**Comment by JenniferBuehler** [comment]
Unfortunately I won't be of much help either, I don't work on Windows. I just make it compile with MinGW for the PR about the move from qmake to CMake... I also tried running it back then and everything worked, but that was about a year ago (?) on an older version of the source...

**Comment by TirawatT** [comment]
Thank you so much.

**Comment by TirawatT** [comment]
Thank you so much.
