### ISSUE TITLE
How can we make not display graspable object coordinates?

### ISSUE THREAD

**Issue by knorth55** [graspit-simulator/graspit#125]
I'm planning to collect RGB image of objects, but it display graspable object coordinates.
How can we make this coordinates not display in captured image?
I want to remove this yellow x-y-z coordinates from the image.
![graspit_coordinates](https://user-images.githubusercontent.com/9300063/29158271-54f24572-7de5-11e7-81a7-1b51e0ba9fe3.png)

**Comment by jvarley** [comment]
![image](https://user-images.githubusercontent.com/1675542/29175462-22e5bee8-7db7-11e7-8fb6-309b58494dfb.png)


![image](https://user-images.githubusercontent.com/1675542/29175479-2aa61128-7db7-11e7-9c4c-395c6e5fca91.png)

![image](https://user-images.githubusercontent.com/1675542/29175484-2ffb26ea-7db7-11e7-8f4c-2943f79058b5.png)

Element->Body Properties  then toggle Show Axes. 


![image](https://user-images.githubusercontent.com/1675542/29175508-3d9eccd4-7db7-11e7-9c97-68c06bca794b.png)


![image](https://user-images.githubusercontent.com/1675542/29175518-41f5529e-7db7-11e7-9107-b1693ef3b30e.png)

If you look in Body.cpp, you can find the body constructor and set showAx variable to false, you may also want to flop off showFC (friction cones) and showVC (virtual contacts. )

**Comment by knorth55** [comment]
thank you so much!
I'm using GraspIt! from graspit_commander, but it seems I cannot do this process via moveit_interface.
Anyway, thank you so much!

**Comment by jvarley** [comment]
You could add functionality to do this to graspit_interface/graspit_commander and make a PR :)

**Comment by knorth55** [comment]
Let me take a look for it!
