### ISSUE TITLE
Make failed with libgraspit.so

### ISSUE THREAD

**Issue by yshiyi** [graspit-simulator/graspit#151]
Hi, guys,
I try to install Graspit on Ubuntu 16.04.
Following the standard procedure, I've got this error after typing in make -j5

libgraspit.so: undefined reference to 'SoInput::setBuffer(void*, unsigned long)'
collect2: error: ld returned 1 exit status
CMakeFiles/graspit_simulator.dir/build.make: 107: recipe for target 'graspit_simulator' failed
make[2]: *** [graspit_simulator] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/grapit_simulator.dir/all' failed
make[2]: *** [CMakeFiles/graspit_simulator.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for any help.

**Comment by jaytjoa** [comment]
hey, have you solved this issue?

**Comment by FezanTab** [comment]
has there been a fix for this issue yet?
