### ISSUE TITLE
Schunk WSG 50

### ISSUE THREAD

**Issue by mattcorsaro1** [graspit-simulator/graspit#155]
Hi,

I'd like to use the Schunk WSG 50 hand. I generated a GraspIt model from [wsg50-ros-pkg](https://github.com/nalt/wsg50-ros-pkg)'s xacro using urdf2graspit. The model is in my fork [here](https://github.com/mattcorsaro1/graspit/tree/wsg_50). When I run the openclose plugin with it, nothing happens and I get this error:

> Robot joint interpolation error
> Interpolation failed!

Any idea what the problem could be? A discussion about the EigenGrasp file is [here](https://github.com/JenniferBuehler/graspit-pkgs/issues/47).

Thank you!
Matt

**Comment by majiqiang** [comment]
Can GRASPIT also use urdf files? how  do you do it? my gripper is similar to robotiq, i'm very confused now!

**Comment by mattcorsaro1** [comment]
You'll need to convert your URDF to a GraspIt robot model using [urdf2graspit](https://github.com/JenniferBuehler/graspit-pkgs/wiki/urdf2graspit)

**Comment by majiqiang** [comment]
> You'll need to convert your URDF to a GraspIt robot model using [urdf2graspit](https://github.com/JenniferBuehler/graspit-pkgs/wiki/urdf2graspit)
OK，thank you very much .What's more, how do you get urdf model? i just know a tool , SolidWorks plugin, maybe convert stl or other 3D model to urdf. I don't know if it's right, so i want to ask for your help.

**Comment by mattcorsaro1** [comment]
Yeah, if you have an stl file, you should be able to generate a URDF with [this plugin](http://wiki.ros.org/sw_urdf_exporter).

**Comment by majiqiang** [comment]
> Yeah, if you have an stl file, you should be able to generate a URDF with [this plugin](http://wiki.ros.org/sw_urdf_exporter).

yeah！ i know this plugin, but i am confused that how to use this plugin, my gripper is complex, it has a parallelogram mechanism link, i don't know how to bulid it. Do you have a good method?

**Comment by mattcorsaro1** [comment]
I edited the defaultVelocity and joint limits in my model and it seems to work now. I'll submit a PR once I've tested it.

**Comment by majiqiang** [comment]
> I edited the defaultVelocity and joint limits in my model and it seems to work now. I'll submit a PR once I've tested it.

Hello，Matt！Honor to receive your reply. Recently I try to export my gripper to urdf file firstly, but i failed. It  looks very irregular in RVIZ. I really don't know how to do, could you help me ?
This is my mesh model with coordinate system and my generated urdf file. And maybe the coordinate is wrong, I don't know.
![pic1](https://user-images.githubusercontent.com/37575460/58618749-fde8c680-82f5-11e9-887a-aee052686c87.png)
![pic2](https://user-images.githubusercontent.com/37575460/58618766-05a86b00-82f6-11e9-9103-54f2dc1fad18.png)
[装配体1.zip](https://github.com/graspit-simulator/graspit/files/3236057/1.zip)
[myurdf.tar.gz](https://github.com/graspit-simulator/graspit/files/3236070/myurdf.tar.gz)

**Comment by majiqiang** [comment]
> I edited the defaultVelocity and joint limits in my model and it seems to work now. I'll submit a PR once I've tested it.

Hello, Matt, could you help me generate urdf file or robot description files? I 'm in trouble!

**Comment by majiqiang** [comment]
![image](https://user-images.githubusercontent.com/37575460/60087911-6fd6f300-9770-11e9-9ca8-e2dddd782a9c.png)
i met same problem!
how do you solve?

> Robot joint interpolation error
Interpolation failed!
