### ISSUE TITLE
how to translate the 3D model stl to  xml and iv?

### ISSUE THREAD

**Issue by majiqiang** [graspit-simulator/graspit#156]
i use our gripper model in graspit based on ubuntu16.04 not ros. i want to build its model's xml file because i want to import ourselves gripper into graspit. Our hand is similar to the robotiq,  thank you!

**Comment by mattcorsaro1** [comment]
You'll need to convert your URDF to a GraspIt robot model using [urdf2graspit](https://github.com/JenniferBuehler/graspit-pkgs/wiki/urdf2graspit)

**Comment by jih189** [comment]
you can use blender to convert it. By the way, remember to repose the object so it can convert.

**Comment by majiqiang** [comment]
> you can use blender to convert it. By the way, remember to repose the object so it can convert.

what is the blender？

**Comment by majiqiang** [comment]
> you can use blender to convert it. By the way, remember to repose the object so it can convert.

what is the blender？

**Comment by jih189** [comment]
check this out https://www.blender.org/. For the method to convert, you can search with google.
