### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jaytjoa** [graspit-simulator/graspit#168]
Hey, I have tried to build the data. First there is an
![Screenshot from 2020-03-24 14-25-29](https://user-images.githubusercontent.com/39117528/77435718-efb6ea00-6de2-11ea-9bb3-3685ee991576.png)
 error with the ivmgr.cpp.
[](url)

so I commented out the lines in 673-676. And it continued to compile until there is an error like this : 

![Screenshot from 2020-03-24 14-27-33](https://user-images.githubusercontent.com/39117528/77435735-f3e30780-6de2-11ea-99cc-118b84cd648e.png)

Any solution for this issue? I am using ubunt 16.04 and already installed all dependencies that I needed to install graspit.

**Comment by Donglin-Wang2** [comment]
Hey @jaytjoa, would you mind sharing how you resolved the problem?
