### ISSUE TITLE
appveyor support

### ISSUE THREAD

**Issue by jvarley** [graspit-simulator/graspit#41]
@JenniferBuehler 

Any idea how difficult it would be to setup something like:
https://github.com/dartsim/dart/blob/master/appveyor.yml

Using your windows instructions? Appveyor is like travis but for Windows.

**Comment by JenniferBuehler** [comment]
Hmm I don't know, it's worth a try... but as a general rule I'd say compiling anything on Windows will be some sort of pain, more or less. Not sure what you want to do... you want to set up appveyor for graspit in a similar fashion as dartsim does?

No other way to tell than to just try ;)
