### ISSUE TITLE
Filling mesh holes in HumanHand16DOF robot

### ISSUE THREAD

**Issue by belledon** [graspit-simulator/graspit#53]
I have been using an automated planner on a database imported from Shapenet. I was wondering if you know of any way to fill the gaps in the HumanHand robot that appear in some grasps (particularly between the base base of the thumb and its insertion into the palm)?

**Comment by jvarley** [comment]
Unfortunately I do not.  I am also concerned that even if you found a rigid body model of the hand that didn't have those gaps it may not be very representative of how the hand actually moves.  I don't know how much that matters to your application. 

I am not aware of any that are better than this. Perhaps

https://github.com/ubi-agni/human_hand

Although this maybe the same one as in GraspIt!
