### ISSUE TITLE
Model list retrieval failed

### ISSUE THREAD

**Issue by xcmax** [graspit-simulator/graspit#66]
I do as the cgdb manual,but it shows model list retrieval failed.There are data in the database when viewed with pgamdin III.

**Comment by jvarley** [comment]
https://github.com/jvarley/graspit/wiki/CGDB-Integration

**Comment by jvarley** [comment]
https://github.com/graspit-simulator/graspit/pull/26

**Comment by Lucksong** [comment]
I also encountered this problem of "Model list retrieval failed", and there is no graspit.pro file in the database version I downloaded.Did anyone solve this problem?
