### ISSUE TITLE
Unable to import worlds

### ISSUE THREAD

**Issue by MrGba2z** [graspit-simulator/graspit#71]
Hi there,

I followed manual (get started chapter) to import dlr_flask.xml. But nothing shows up in my window. Am I missing something or is the manual out of date?

Thanks

environment: Ubuntu LTS 16.04.01
![](http://i.imgur.com/3kYwOhs.jpg)

**Comment by jvarley** [comment]
In the terminal you are running GraspIt! is anything printed out when you run launch graspit and open the world?

Also in that same terminal, could you please run:
```
env | grep GRASPIT
```

**Comment by MrGba2z** [comment]
Oh, I did't try to run it in terminal.  
The environment setting (GRASPIT) is ok. It's set to the graspit home path correctly.

Everything is good when I start it in command line.(already solves my problem)  
But when I double click the application in the GUI. It raises my problem.

**Comment by jvarley** [comment]
What GUI are you referring to, GraspIt! or an IDE?

**Comment by MrGba2z** [comment]
Oh, I am talking about the ubuntu GUI.
What I did is just double click the executable graspit_simulator in /build folder.
![](http://i.imgur.com/WdA8Dvv.png)

**Comment by jvarley** [comment]
Got it. Yes, it is not working because the GRASPIT environment variable is not set when you launch it this way.  Graspit uses that environment variable to locate the worlds, and models subdirectories.  I would recommend launching it from the terminal, because you will also be able to see any output messages from Graspit while it is running.

**Comment by jvarley** [comment]
If you really want to run it from the GUI, then make a small bash script and place it next to graspit_simulator call it run.sh:

#!/bin/bash                                                                     
export GRASPIT=/home/jvarley/graspit
./graspit_simulator

**Comment by MrGba2z** [comment]
Thanks for the help!

**Comment by Elmigdad** [comment]
hello 
how do i open Graspit! via terminal!?
and how to create my own model

**Comment by Elmigdad** [comment]
hello 
I have created my robot hand, but there is an issue of miss matching between geometry and axis of rotation .. how do I fix it please ???
